### PR TITLE
Make Zuul CI a 3rd party one

### PR DESCRIPTION
**Pull request by ssbarnea**
Instead of relying on Zuul to gate project changes we only
use zuul checks in order to run tests on platforms that are not
well supported by github actions.

### CODE REVIEW

**Comment by goldyfruit** [comment]
I guess this PR should solve this error in Zuul.
```
Unfortunately, GitHub does not allow GitHub applications the ability merge changes to these files. As a result, Zuul will not be able to merge your pull requests.  Please delete this folder.
```

**Comment by ssbarnea** [comment]
> I guess this PR should solve this error in Zuul.
> 
> ```
> Unfortunately, GitHub does not allow GitHub applications the ability merge changes to these files. As a result, Zuul will not be able to merge your pull requests.  Please delete this folder.
> ```

You are right. It will sort that error and run Zuul as a 3rd party CI. It will report but not really preventing merges.

Are you interested to help with development of molecule-libvirt? I can send you an invite.

**Comment by goldyfruit** [comment]
> Are you interested to help with development of molecule-libvirt? I can send you an invite.

Actually I'm working with @jamesregis so why not! :)

**Comment by pabelanger** [comment]
@ssbarnea can you please remove molecule-libvirt from the check pipeline for zuul?

Thanks

**Pull request merged**
