### PR TITLE
[zuul] Use Python 3.9 with Fedora 34

### PR DESCRIPTION
**Pull request by goldyfruit**
Zuul complains about python38-devel package not available.
Default Python version on Fedora 34 is Python 3.9.

This should fix issue #29.

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1205
Depends-On: https://github.com/ansible/ansible/ansible-zuul-jobs#1210

### CODE REVIEW

**Comment by jseguillon** [comment]
```
py39-devel: could not install deps [ansible>=2.10.0a2,<2.11, molecule[test], 
git+https://github.com/ansible-community/molecule.git@master#egg=molecule[test], selinux]
```

Need to change from "master" to "main"  git branch

**Comment by goldyfruit** [comment]
> ```
> py39-devel: could not install deps [ansible>=2.10.0a2,<2.11, molecule[test], 
> git+https://github.com/ansible-community/molecule.git@master#egg=molecule[test], selinux]
> ```
> 
> Need to change from "master" to "main" git branch
> 
> See #29

Yeah we just wanted to see if `python39-devel` was still missing. :)
The PR is in progress on the Zuul jobs side _(@goneri is helping me with this)_.

**Comment by goldyfruit** [comment]
recheck

**Comment by goldyfruit** [comment]
recheck

**Comment by goldyfruit** [comment]
recheck

**Comment by goldyfruit** [comment]
So I guess I'll have to do a new PR for Fedora 34

**Review by ssbarnea — APPROVED** [review]

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
recheck

**Comment by ssbarnea** [comment]
recheck

**Comment by ssbarnea** [comment]
recheck

**Comment by ssbarnea** [comment]
recheck

**Comment by ssbarnea** [comment]
recheck

**Comment by ssbarnea** [comment]
recheck

**Comment by goneri** [comment]
Can you try https://github.com/ansible/ansible-zuul-jobs/pull/1210?

**Comment by goldyfruit** [comment]
recheck

**Comment by goldyfruit** [comment]
Yeah \o/
Thanks @ssbarnea

**Pull request merged**
